=== EsupPortail/esup-lecture/src/main/resources/properties/esup-lecture.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT channelConfig (ttl?, userId?, guestUser?, context*, categoryProfile*)>

<!ELEMENT userId (#PCDATA)> <!-- deprecated since 0.8.4 -->
<!ELEMENT guestUser (#PCDATA)>
<!ELEMENT ttl (#PCDATA)>
<!ELEMENT context (description,refCategoryProfile*,categoryProfilesUrl*)>
<!ATTLIST context
    name CDATA #REQUIRED
	id ID #REQUIRED
    treeVisible (yes|no|forceNo) "yes"
    edit (all|personal|managed|no) "no">

<!ELEMENT description (#PCDATA)>

<!ELEMENT refCategoryProfile EMPTY>
<!ATTLIST refCategoryProfile
    refId IDREF #REQUIRED>

<!ELEMENT categoryProfilesUrl EMPTY>
<!ATTLIST categoryProfilesUrl
    url CDATA #REQUIRED
    timeout CDATA #REQUIRED
    idPrefix CDATA #IMPLIED>

<!ELEMENT categoryProfile (visibility)>
<!ATTLIST categoryProfile
    id ID #REQUIRED
	name CDATA #REQUIRED
    urlCategory CDATA #REQUIRED
    trustCategory (yes|no) "no"
    edit (all|personal|managed|no) "no"
    access (public|cas) "public"
    userCanMarkRead (yes|no) "yes"
    specificUserContent (yes|no) "no"
    ttl CDATA #REQUIRED
    timeout CDATA #REQUIRED>

<!ELEMENT visibility (allowed,autoSubscribed,obliged)>

<!ELEMENT allowed (regular*, regex*, group*, guest?)>
<!ELEMENT autoSubscribed (regular*, regex*, group*, guest?)>
<!ELEMENT obliged (regular*, regex*, group*, guest?)>

<!ELEMENT regular EMPTY>
<!ATTLIST regular
    attribute CDATA #REQUIRED
    value CDATA #REQUIRED>

<!ELEMENT regex EMPTY>
<!ATTLIST regex
    attribute CDATA #REQUIRED
    pattern CDATA #REQUIRED>

<!ELEMENT group EMPTY>
<!ATTLIST group
    name CDATA #REQUIRED>

=== EsupPortail/esup-lecture/src/main/resources/properties/esup-lecture.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE channelConfig SYSTEM "esup-lecture.dtd" >
<channelConfig>
	<guestUser>guest</guestUser>
	<context 
	  name = "Très beau context1"
	  id = "c1">
	  <description>C'est le context 1</description> 
	  <refCategoryProfile refId="cp1"/>
  	  <refCategoryProfile refId="cp2"/>
  	  <refCategoryProfile refId="cp3"/>
  	  <refCategoryProfile refId="cp4"/>
  	  <refCategoryProfile refId="cp5"/>
	</context>
	
	<context 
	  name = "context2"
	  id = "c2">
	  <description>C'est le context 2</description> 
	  <refCategoryProfile refId="cp1"/>
  	  <refCategoryProfile refId="cp2"/>
 	</context>

	<context 
	  name = "context3"
	  id = "c3">
	  <description>C'est le context 3</description> 
  	  <refCategoryProfile refId="cp2"/>
  	  <refCategoryProfile refId="cp3"/>
  	  <refCategoryProfile refId="cp4"/>  
	</context>

	<context 
	  name = "Démonstration Esup-Lecture"
	  id = "default">
	  <description><![CDATA[
<h1>Contexte de d&eacute;monstration</h1>
D&eacute;monstration du canal Lecture.<br>
<br>
Pour plus d'informations voir le 
<a target="_blank" href="http://sourcesup.cru.fr/projects/esup-lecture">site du projet</a>
	  ]]></description> 
  	  <refCategoryProfile refId="demo1"/>
  	  <refCategoryProfile refId="demo2"/>
<!-- 
  	  <refCategoryProfile refId="demo3"/>
 -->  	  
	</context>

	<categoryProfile 
		name="categorie1 : no trust cat"		
		id="cp1"
		urlCategory="http://partages.univ-rennes1.fr/files/partages/Services/CRI/SI/conf_lecture_gwe_ray/categoryTest.xml"
		trustCategory="no"
		access="public"
		ttl = "3600"
		timeout = "3000" >
		<visibility>
			<allowed/>
			<autoSubscribed/>
			<obliged>
				<regular
					attribute="sn"
					value="User"/>					
			</obliged>
		</visibility>
	</categoryProfile>
	
 	<categoryProfile 
		name="categorie2 : no trust cat"	
		id="cp2"
		urlCategory="http://partages.univ-rennes1.fr/files/partages/Services/CRI/SI/conf_lecture_gwe_ray/categoryTest.xml"
		trustCategory="no"
		access="public"
		ttl = "3600"
		timeout = "3000">
	 	<visibility>
	 		<allowed/>
			<autoSubscribed/>
			<obliged>	
				<group
					name="local.0"/>
			</obliged>	
		</visibility>
	</categoryProfile>
	
	<categoryProfile 
		name="categorie3 : no trust cat"
		id="cp3"
		urlCategory="http://partages.univ-rennes1.fr/files/partages/Services/CRI/SI/conf_lecture_gwe_ray/categoryTest.xml"
		trustCategory="no"
		access="public"
		ttl = "3600"
		timeout = "3000"  >
		<visibility>
			<allowed/> 
			<autoSubscribed/>
			<obliged>
				<regular
					attribute="sn"
					value="Useppr"/>					
			</obliged>
		</visibility>
	</categoryProfile>
	
	<categoryProfile 
		name="categorie4  : no trust cat"
		id="cp4"
		urlCategory="http://partages.univ-rennes1.fr/files/partages/Services/CRI/SI/conf_lecture_gwe_ray/categoryTest.xml"
		trustCategory="no"
		access="public"
		ttl = "3600"
		timeout = "3000"  > 
		<visibility>
			<allowed/>
			<autoSubscribed/>
			<obliged>	
				<group
					name="local.0"/>
			</obliged>	
		</visibility>
	</categoryProfile>

	<categoryProfile 
		name="categorie5  : trust cat"
		id="cp5"
		urlCategory="http://partages.univ-rennes1.fr/files/partages/Services/CRI/SI/conf_lecture_gwe_ray/categoryTest.xml"
		trustCategory="yes"
		access="public"
		ttl = "3600"
		timeout = "3000"  > 
		<visibility>
			<allowed/>
			<autoSubscribed/>
			<obliged>	
				<group
					name="local.0"/>
			</obliged>	
		</visibility>
	</categoryProfile>

	<categoryProfile 
		name="Categorie de démo 1"
		id="demo1"
		urlCategory="${config.url.prefix}/category.offline.xml"
		trustCategory="yes"
		access="public"
		ttl = "3600" 
		timeout = "3000" > 
		<visibility>
			<allowed/>
			<autoSubscribed/>
			<obliged>	
				<group
					name="local.0"/>
			</obliged>	
		</visibility>
	</categoryProfile>
		
	<categoryProfile 
		name="Categorie de démo 2"
		id="demo2"
		urlCategory="http://partages.univ-rennes1.fr/files/partages/Services/CRI/SI/conf_lecture_gwe_ray/demo2.xml"
		trustCategory="no"
		access="public"
		ttl = "3600" 
		timeout = "3000" > 
		<visibility>
			<allowed/>
			<autoSubscribed/>
			<obliged>	
				<group
					name="local.0"/>
			</obliged>	
		</visibility>
	</categoryProfile>
		
	<categoryProfile 
		name="Categorie de démo 3"
		id="demo3"
		urlCategory="http://partages.univ-rennes1.fr/files/partages/Services/CRI/SI/conf_lecture_gwe_ray/demo3.xml"
		trustCategory="yes"
		access="public"
		ttl = "3600"
		timeout = "3000"  > 
		<visibility>
			<allowed/>
			<autoSubscribed/>
			<obliged>	
				<group
					name="local.0"/>
			</obliged>	
		</visibility>
	</categoryProfile>
		
	<categoryProfile 
		name="Categorie de démo 4"
		id="demo4"
		urlCategory="http://partages.univ-rennes1.fr/files/partages/Services/CRI/SI/conf_lecture_gwe_ray/demo4.xml"
		trustCategory="yes"
		access="public"
		ttl = "3600"
		timeout = "3000"  > 
		<visibility>
			<allowed/>
			<autoSubscribed/>
			<obliged>	
				<group
					name="local.0"/>
			</obliged>	
		</visibility>
	</categoryProfile>
		
</channelConfig>

=== EsupPortail/esup-lecture/src/test/resources/properties/esup-lecture.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE channelConfig SYSTEM "esup-lecture.dtd" >
<channelConfig>
	<guestUser>guest</guestUser>
    <context
            name="Démonstration Esup-Lecture"
            id="saisieSimplifiee">
        <description></description>
        <refCategoryProfile refId="demo1"/>
        <refCategoryProfile refId="demo2"/>
        <refCategoryProfile refId="news2-1"/>
        <refCategoryProfile refId="news2-2"/>
    </context>

    <context
            name="Démonstration Esup-Lecture"
            id="saisieNormale">
        <description></description>
        <refCategoryProfile refId="demo1"/>
        <refCategoryProfile refId="demo2"/>
    </context>

    <categoryProfile
		name="Categorie de démo 1"
		id="demo1"
		urlCategory="${config.url.prefix}/examples/xml/category.offline.xml"
		trustCategory="no"
		access="public"
		ttl = "3600"
		timeout = "3000" >
		<visibility>
			<allowed/>
			<autoSubscribed/>
			<obliged>
				<group name="local.0"/>
			</obliged>
		</visibility>
	</categoryProfile>

	<categoryProfile
		name="Categorie de démo 2"
		id="demo2"
		urlCategory="${config.url.prefix}/examples/xml/demo2.xml"
		trustCategory="no"
		access="public"
		ttl = "3600"
		timeout = "3000" >
		<visibility>
			<allowed/>
			<autoSubscribed/>
			<obliged>
				<group name="local.0"/>
			</obliged>
		</visibility>
	</categoryProfile>

    <categoryProfile
            name="Catégorie (saisie simplifié de News 2)"
            id="news2-1"
            urlCategory="${config.url.prefix}/examples/xml/category.offline.xml"
            trustCategory="no"
            access="public"
            ttl="3600"
            timeout="3000"
            groupCategory="true"
            entity="Catégorie News 2">
        <visibility>
            <allowed/>
            <autoSubscribed/>
            <obliged>
                <group
                        name="local.0"/>
            </obliged>
        </visibility>
    </categoryProfile>

    <categoryProfile
            name="Categorie de démo 2"
            id="news2-2"
            urlCategory="${config.url.prefix}/examples/xml/demo2.xml"
            trustCategory="no"
            access="public"
            ttl = "3600"
            timeout = "3000"
            groupCategory="true"
            entity="Catégorie News 2">
        <visibility>
            <allowed/>
            <autoSubscribed/>
            <obliged>
                <group name="local.0"/>
            </obliged>
        </visibility>
    </categoryProfile>

</channelConfig>
