=== EsupPortail/esup-lecture/src/main/resources/properties/mappings.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT mappings (mapping+)>

<!ELEMENT mapping (XPathNameSpace*)>
<!ATTLIST mapping 
	sourceURL CDATA #IMPLIED
    dtd CDATA #IMPLIED
    xmlns CDATA #IMPLIED
    xmlType CDATA #IMPLIED
    rootElement CDATA #IMPLIED
    xsltFile CDATA #REQUIRED
    mobileXsltFile CDATA #IMPLIED
    itemXPath CDATA #REQUIRED>
    
<!ELEMENT XPathNameSpace EMPTY>
<!ATTLIST XPathNameSpace 
	prefix CDATA #REQUIRED
	uri CDATA #REQUIRED>

=== EsupPortail/esup-lecture/src/main/resources/properties/mappings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings SYSTEM "mappings.dtd" >

<!-- examples of mapping for applying xsl transformation to xml sources 
See projet documentation for complete syntax reference
xlstFiles given here are only samples and must be copied and modified on your own domain
-->
<mappings>
<!-- 
	<mapping 
		sourceURL="http://info.cri.univ-rennes1.fr/rss/rss.php"
		xsltFile="http://partages.univ-rennes1.fr/files/partages/Services/CRI/SI/conf_lecture_gwe_ray/stylesheet01.xsl"
		itemXPath="/rdf:RDF/default:item">
		<XPathNameSpace prefix="rdf" uri="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
		<XPathNameSpace prefix="default" uri="http://purl.org/rss/1.0/" />
	</mapping>
 -->
	<mapping 
		sourceURL="${config.url.prefix}/examples/xml/flux.offline1.xml"
		xsltFile="${config.url.prefix}/examples/xsl/rss-jquery-clickable.xsl"
		mobileXsltFile="${config.url.prefix}/examples/xsl/rss-mobile.xsl"
		itemXPath="/rss/channel/item">
	</mapping>
	<mapping 
		sourceURL="${config.url.prefix}/examples/xml/flux.offline2.xml"
		xsltFile="${config.url.prefix}/examples/xsl/rss-jquery-inline.xsl"
		mobileXsltFile="${config.url.prefix}/examples/xsl/rss-mobile.xsl"
		itemXPath="/rss/channel/item">
	</mapping>
	<mapping 
		sourceURL="${config.url.prefix}/examples/xml/flux.offline3.xml"
		xsltFile="${config.url.prefix}/examples/xsl/rss-jquery-dialog.xsl"
		mobileXsltFile="${config.url.prefix}/examples/xsl/rss-mobile.xsl"
		itemXPath="/rss/channel/item">
	</mapping>
	<mapping 
		rootElement="rss"
		xsltFile="${config.url.prefix}/examples/xsl/rss-jquery-inline.xsl"
		mobileXsltFile="${config.url.prefix}/examples/xsl/rss-mobile.xsl"
		itemXPath="/rss/channel/item">
	</mapping>
<!-- Same format as above, but with thickbox style : comment one of them -->
<!--
	<mapping 
		rootElement="rss"
		xsltFile="http://partages.univ-rennes1.fr/files/partages/Services/CRI/SI/conf_lecture_gwe_ray/rss-thickbox.xsl"
		itemXPath="/rss/channel/item">
	</mapping>
-->

	<mapping 
		rootElement="RDF"
		xsltFile="${config.url.prefix}/examples/xsl/rdf.xsl"
		itemXPath="/rdf:RDF/default:item">
		<XPathNameSpace prefix="rdf" uri="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
		<XPathNameSpace prefix="default" uri="http://purl.org/rss/1.0/" />
	</mapping>

	<mapping 
		rootElement="flash"
		xsltFile="${config.url.prefix}/examples/xsl/flash.xsl"
		itemXPath="/flash/object">
	</mapping>

	<mapping 
		rootElement="java"
		xsltFile="${config.url.prefix}/examples/xsl/java.xsl"
		itemXPath="/java/applet">
	</mapping>
</mappings>

=== EsupPortail/esup-lecture/properties/mappings.test.domain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings SYSTEM "mappings.dtd" [
<!ENTITY repConf "file:///d:/tmp/conf_lecture_gwe_ray/" >
] >
<mappings>
	<mapping 
		sourceURL="http://info.cri.univ-rennes1.fr/rss/rss.php"
		xsltFile="&repConf;stylesheet01.xsl"
		itemXPath="/rdf:RDF/default:item">
		<XPathNameSpace prefix="rdf" uri="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
		<XPathNameSpace prefix="default" uri="http://purl.org/rss/1.0/" />
	</mapping>
	<mapping 
		rootElement="rss"
		xsltFile="&repConf;stylesheet02.xsl"
		itemXPath="/rss/channel/item">
	</mapping>
	<mapping 
		rootElement="flash"
		xsltFile="&repConf;flash.xsl"
		itemXPath="/flash/object">
	</mapping>
	<mapping 
		rootElement="java"
		xsltFile="&repConf;java.xsl"
		itemXPath="/java/applet">
	</mapping>
	<mapping 
		rootElement="iframes"
		xsltFile="&repConf;java.xsl"
		itemXPath="/iframes/iframe">
	</mapping>
</mappings>

=== EsupPortail/esup-lecture/properties/mappings.example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings SYSTEM "mappings.dtd" [
<!ENTITY repConf "file:///data/webapps/ent.univ-rennes1.fr/application/esup-lecture/properties" >
<!ENTITY httpConf "http://ent.univ-rennes1.fr/"
] 
>
<!-- examples of mapping for applying xsl transformation to xml sources 
See projet documentation for complete syntax reference
xlstFiles given here are only samples and must be copied and modified on your own domain
-->
<mappings>
	<mapping 
		sourceURL="http://ent.univ-rennes1.fr/newsPortlet/"
		xsltFile="&repConf;rss-newsPortlet.example.xsl"
		itemXPath="/rss/channel/item">
	</mapping>
	<mapping 
		sourceURL="http://demo.ori-oai.org/search/advanced-search.htm"
		xsltFile="&repConf;rss-newsPortlet.example.xsl"
		itemXPath="/rss/channel/item">
	</mapping>
	<mapping 
		sourceURL="http://www.univ-rennes1.fr/bas-de-page/RSS/actualites/"
		xsltFile="&repConf;actu-infoglue.example.xsl"
		itemXPath="/rdf:RDF/default:item">
		<XPathNameSpace prefix="rdf" uri="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
		<XPathNameSpace prefix="default" uri="http://purl.org/rss/1.0/" />
	</mapping>
	<mapping 
		rootElement="rdf:RDF"
		xsltFile="&repConf;rss.example.xsl"
		itemXPath="/rdf:RDF/default:item">
		<XPathNameSpace prefix="rdf" uri="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
		<XPathNameSpace prefix="default" uri="http://purl.org/rss/1.0/" />
	</mapping>
	<mapping 
		rootElement="RDF"
		xsltFile="&repConf;rss.example.xsl"
		itemXPath="/rdf:RDF/default:item">
		<XPathNameSpace prefix="rdf" uri="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
		<XPathNameSpace prefix="default" uri="http://purl.org/rss/1.0/" />
	</mapping>
	<mapping 
		rootElement="rdf"
		xsltFile="&repConf;rss.example.xsl"
		itemXPath="/rdf:RDF/default:item">
		<XPathNameSpace prefix="rdf" uri="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
		<XPathNameSpace prefix="default" uri="http://purl.org/rss/1.0/" />
	</mapping>
	<mapping 
		rootElement="rss"
		xsltFile="&repConf;rss-simple.example.xsl"
		itemXPath="/rss/channel/item">
	</mapping>
	<mapping 
		rootElement="flash"
		xsltFile="&repConf;flash.example.xsl"
		itemXPath="/flash/object">
	</mapping>
	<mapping 
		rootElement="java"
		xsltFile="&repConf;java.example.xsl"
		itemXPath="/java/applet">
	</mapping>
	<mapping 
		rootElement="iframes"
		xsltFile="&repConf;java.example.xsl"
		itemXPath="/iframes/iframe">
	</mapping>

</mappings>
