=== EsupPortail/esup-lecture/properties/category.dtd
<!ELEMENT category (description,sourceProfiles, visibility?)>
<!ATTLIST category 
    name CDATA #REQUIRED
    edit (all|personal|managed|no) "no">
<!ELEMENT description (#PCDATA)>     
<!ELEMENT sourceProfiles (sourceProfile+)>

<!ELEMENT sourceProfile (visibility?)>
<!ATTLIST sourceProfile 
	id ID #REQUIRED
    name CDATA #REQUIRED
    url CDATA #REQUIRED
    xslt CDATA #IMPLIED
    xpath CDATA #IMPLIED
    access (public|cas) #IMPLIED
    specificUserContent (yes|no) "no"
    timeout CDATA #IMPLIED>

<!ELEMENT visibility (allowed,autoSubscribed,obliged)>

<!ELEMENT allowed (regular*, group*)>
<!ELEMENT autoSubscribed (regular*, group*)>
<!ELEMENT obliged (regular*, group*)>

<!ELEMENT regular EMPTY>
<!ATTLIST regular 
    attribute CDATA #REQUIRED
    value CDATA #REQUIRED>

<!ELEMENT group EMPTY>
<!ATTLIST group name CDATA #REQUIRED>

=== EsupPortail/esup-lecture/properties/rss-rennes1.example.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE category SYSTEM "category.dtd">
<category edit="all" name="Fils RSS de l'université" ttl="">
	<description>Fils RSS Rennes 1</description>
	
	<sourceProfiles>
		<sourceProfile id="un" access="public" name="Site de l'université" 
		 specificUserContent="no" ttl="86400" url="http://www.univ-rennes1.fr/bas-de-page/RSS/ENT/RSS-toutes-les-actus">
			<visibility>
			    <obliged>
				<group name="local.0"/>  <!-- Tous les groupes de personnes -->
				<group name="local.15"/> <!-- Anonymes -->
			    </obliged>
			</visibility>		
		</sourceProfile>
		<sourceProfile id="deux" access="public" name="Etat des réseaux et services" 
		 specificUserContent="no" ttl="3600" url="http://info.cri.univ-rennes1.fr/rss/rss.php">
			<visibility>
			    <obliged>
				<group name="local.0"/>  <!-- Tous les groupes de personnes -->
				<group name="local.15"/> <!-- Anonymes -->
			    </obliged>
			</visibility>		
		</sourceProfile>
	</sourceProfiles>
	
	<visibility>
		<obliged>
			<group name="local.0"/>  <!-- Tous les groupes de personnes -->
			<group name="local.15"/> <!-- Anonymes -->
		</obliged>
	</visibility>
</category>

=== EsupPortail/esup-lecture/properties/rss-canalu.example.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE category SYSTEM "category.dtd">
<category edit="all" name="Canal-U" ttl="60">
	<description>Flux RSS canal-U</description>
	
	<sourceProfiles>
		<sourceProfile id="un" access="public" name="Podcasts Droit" 
		 specificUserContent="no" ttl="60" url="http://www.canal-u.tv/layout/set/xml/content/view/podcast-theme/101/%28idTheme%29/60/">
			<visibility>
				<allowed>
					<group name="local.0"/>
					<group name="local.15"/>
				</allowed>
				<autoSubscribed/>
				<obliged>
					<group name="local.14"/> <!-- Admins -->
				</obliged>
			</visibility>		
		</sourceProfile>
		<sourceProfile id="deux" access="public" name="Podcasts Economie et Gestion" 
		 specificUserContent="no" ttl="60" url="http://www.canal-u.tv/layout/set/xml/content/view/podcast-theme/101/%28idTheme%29/61/">
			<visibility>
				<allowed>
					<group name="local.0"/>
					<group name="local.15"/>
				</allowed>
				<autoSubscribed/>
				<obliged>
					<group name="local.14"/> <!-- Admins -->
				</obliged>
			</visibility>		
		</sourceProfile>
		<sourceProfile id="trois" access="public" name="Podcasts Environnement et développement durable" 
		 specificUserContent="no" ttl="60" url="http://www.canal-u.tv/layout/set/xml/content/view/podcast-theme/101/%28idTheme%29/62/">
			<visibility>
				<allowed>
					<group name="local.0"/>
					<group name="local.15"/>
				</allowed>
				<autoSubscribed/>
				<obliged>
					<group name="local.14"/> <!-- Admins -->
				</obliged>
			</visibility>		
		</sourceProfile>
		<sourceProfile id="quatre" access="public" name="Podcasts Lettres, Arts, Langues et Civilisations" 
		 specificUserContent="no" ttl="60" url="http://www.canal-u.tv/layout/set/xml/content/view/podcast-theme/101/%28idTheme%29/63/">
			<visibility>
				<allowed>
					<group name="local.14"/> <!-- Admins -->
				</allowed>
				<autoSubscribed/>
				<obliged>
				</obliged>
			</visibility>		
		</sourceProfile>
		<sourceProfile id="cinq" access="public" name="Podcasts Sciences de la santé et du sport" 
		 specificUserContent="no" ttl="60" url="http://www.canal-u.tv/layout/set/xml/content/view/podcast-theme/101/%28idTheme%29/64/">
			<visibility>
				<allowed>
					<group name="local.14"/> <!-- Admins -->
				</allowed>
				<autoSubscribed/>
				<obliged>
				</obliged>
			</visibility>		
		</sourceProfile>
		<sourceProfile id="six" access="public" name="Podcasts Sciences de l'ingenieur" 
		 specificUserContent="no" ttl="60" url="http://www.canal-u.tv/layout/set/xml/content/view/podcast-theme/101/%28idTheme%29/68/">
			<visibility>
				<allowed>
					<group name="local.14"/> <!-- Admins -->
				</allowed>
				<autoSubscribed/>
				<obliged>
				</obliged>
			</visibility>		
		</sourceProfile>
		<sourceProfile id="sept" access="public" name="Podcasts Sciences fondamentales" 
		 specificUserContent="no" ttl="60" url="http://www.canal-u.tv/layout/set/xml/content/view/podcast-theme/101/%28idTheme%29/67/">
			<visibility>
				<allowed>
					<group name="local.14"/> <!-- Admins -->
				</allowed>
				<autoSubscribed/>
				<obliged>
				</obliged>
			</visibility>		
		</sourceProfile>
		<sourceProfile id="huit" access="public" name="Podcasts Sciences humaines, sociales, de l'éducation et de l'information" 
		 specificUserContent="no" ttl="60" url="http://www.canal-u.tv/layout/set/xml/content/view/podcast-theme/101/%28idTheme%29/66/">
			<visibility>
				<allowed>
					<group name="local.14"/> <!-- Admins -->
				</allowed>
				<autoSubscribed/>
				<obliged>
				</obliged>
			</visibility>		
		</sourceProfile>
		
	</sourceProfiles>
</category>

=== EsupPortail/esup-lecture/properties/presse.example.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE category SYSTEM "category.dtd">
<category edit="all" name="Presse" ttl="">
	<description>Actualités de la ville de Rennes</description>
	<sourceProfiles>
		<sourceProfile id="un" access="public" name="LeMonde.fr : A la une" 
		 specificUserContent="no" ttl="86400" url="http://www.lemonde.fr/rss/une.xml">
			<visibility>
				<obliged>
					<group name="local.0"/>  <!-- Tous les groupes de personnes -->
					<group name="local.15"/> <!-- Anonymes -->
				</obliged>
			</visibility>		
		</sourceProfile>
		
		<sourceProfile id="deux" access="public" name="LeMonde.fr : International" 
		 specificUserContent="no" ttl="86400" url="http://www.lemonde.fr/rss/sequence/0,2-3210,1-0,0.xml">
			<visibility>
				<obliged>
					<group name="local.0"/>  <!-- Tous les groupes de personnes -->
					<group name="local.15"/> <!-- Anonymes -->
				</obliged>
			</visibility>		
		</sourceProfile>
		
		<sourceProfile id="trois" access="public" name="L'Equipe.fr : Actu Sport" 
		 specificUserContent="no" ttl="86400" url="http://www.lequipe.fr/Xml/actu_rss.xml">
			<visibility>
				<obliged>
					<group name="local.0"/>  <!-- Tous les groupes de personnes -->
					<group name="local.15"/> <!-- Anonymes -->
				</obliged>
			</visibility>		
		</sourceProfile>
		
	</sourceProfiles>
	<visibility>
		<obliged>
			<group name="local.0"/>
			<group name="local.15"/>
		</obliged>
	</visibility>
</category>

=== EsupPortail/esup-lecture/webpages/resources/categoryTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE category SYSTEM "category.dtd" >
<category edit="all" name="TTTTTTTTT" ttl="">
  <description>description</description>
  <sourceProfiles>
    <sourceProfile id="1" access="public" name="toto" specificUserContent="no" ttl="100" url="http://test" xpath="test" xslt="test">
      <visibility>
      <allowed>
      	<regular attribute="attribute1.1" value="value1.1" />
      	<regular attribute="attribute1.2" value="value1.2" />
      	<group name="grp1.1" />
      	<group name="grp1.2" />
      </allowed>
      <autoSubscribed>
      	<regular attribute="attribute2.1" value="value2.1" />
      	<regular attribute="attribute2.2" value="value2.2" />
      	<group name="grp2.1" />
      	<group name="grp2.2" />
      </autoSubscribed>
      <obliged>
      	<regular attribute="attribute3.1" value="value3.1" />
      	<regular attribute="attribute3.2" value="value3.2" />
      	<group name="grp3.1" />
      	<group name="grp3.2" />
      </obliged>
      </visibility>
    </sourceProfile>
    <sourceProfile id="2" access="public" name="toto2" specificUserContent="no" ttl="100" url="http://test" xpath="test" xslt="test">
      <visibility>
      </visibility>
    </sourceProfile>
    <sourceProfile id="3" access="cas" name="toto3" specificUserContent="no" ttl="100" url="http://test" xpath="test" xslt="test">
      <visibility>
      </visibility>
    </sourceProfile>
  </sourceProfiles>
      <visibility>
      <allowed>
      	<regular attribute="attribute4.1" value="value4.1" />
      	<regular attribute="attribute4.2" value="value4.2" />
      	<group name="grp4.1" />
      	<group name="grp4.2" />
      </allowed>
      <autoSubscribed>
      	<regular attribute="attribute4.1" value="value4.1" />
      	<regular attribute="attribute4.2" value="value4.2" />
      	<group name="grp4.1" />
      	<group name="grp4.2" />
      </autoSubscribed>
      <obliged>
      	<regular attribute="attribute4.1" value="value4.1" />
      	<regular attribute="attribute4.2" value="value4.2" />
      	<group name="grp4.1" />
      	<group name="grp4.2" />
      </obliged>
      </visibility>
</category>
