=== EsupPortail/esup-lecture/properties/clecture.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT channelConfig (context+, categoryProfile+)>
<!ATTLIST channelConfig 
    mappingFile CDATA #REQUIRED>

<!ELEMENT context (description,refCategoryProfile*)>
<!ATTLIST context
    name CDATA #REQUIRED
	id ID #REQUIRED
    edit (all|personal|managed|no) "no">

<!ELEMENT description (#PCDATA)>

<!ELEMENT refCategoryProfile EMPTY>
<!ATTLIST refCategoryProfile 
    refId IDREF #REQUIRED>

<!ELEMENT categoryProfile (description,visibility)>
<!ATTLIST categoryProfile
    id ID #REQUIRED
	name CDATA #REQUIRED
    urlCategory CDATA #REQUIRED
    display (all|push-end|read|not-read) "all"	
    trustCategory (yes|no) "no"
    edit (all|personal|managed|no) "no"
    access (public|cas) "public"
    ttl CDATA #REQUIRED>	
    
<!ELEMENT visibility (allowed,autoSubscribed,obliged)>

<!ELEMENT allowed (regular*, group*)>
<!ELEMENT autoSubscribed (regular*, group*)>
<!ELEMENT obliged (regular*, group*)>

<!ELEMENT regular EMPTY>
<!ATTLIST regular 
    attribute CDATA #REQUIRED
    value CDATA #REQUIRED>

<!ELEMENT group EMPTY>
<!ATTLIST group 
    name CDATA #REQUIRED>

=== EsupPortail/esup-lecture/properties/lecture-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE channelConfig SYSTEM "clecture.dtd" >
<channelConfig>
	<!-- user attribute used to create a user profile -->
	<userId>displayName</userId>
	<context 
	  name = "TrÃ¨s beau context1"
	  id = "c1">
	  <description>C'est le context 1 ZZZZZZZZZZZZZZZ</description> 
	  <refCategoryProfile refId="cp1"/>
  	  <refCategoryProfile refId="cp2"/>
  	  <refCategoryProfile refId="cp3"/>
  	  <refCategoryProfile refId="cp4"/>
	</context>
	<context 
	  name = "context2"
	  id = "c2">
	  <description>C'est le context 2</description> 
	  <refCategoryProfile refId="cp1"/>
  	  <refCategoryProfile refId="cp2"/>
 	</context>
	<context 
	  name = "context3"
	  id = "c3">
	  <description>C'est le context 3</description> 
  	  <refCategoryProfile refId="cp2"/>
  	  <refCategoryProfile refId="cp3"/>
  	  <refCategoryProfile refId="cp4"/>  
	</context>
	<!-- JE VOIS -->
	<categoryProfile 
		name="categorie1"
		
		id="cp1"
		urlCategory="http://perso.univ-rennes1.fr:8080/raymond.bourges/categoryTest.xml"
		trustCategory="no"
		access="public"
		ttl = "3600" >
		<visibility>
			<allowed>
				<regular
					attribute="attr11"
					value="val11"/>
				<regular
					attribute="attr112"
					value="val112"/>
				<group
					name="group11"/>
				<group
					name="group112"/>
				<group
					name="group113"/>
				<group
					name="local.4"/>
			</allowed>
			<!-- autoSubscribed not yet supported -->
			<autoSubscribed>
				<regular
					attribute="attr12"
					value="val12"/>
				<group
					name="group12"/>
				<group
					name="group122"/>
			</autoSubscribed>
			<obliged>
				<regular
					attribute="sn"
					value="User"/>	
				
			</obliged>
		</visibility>
	</categoryProfile>
	 <!-- JE VOIS -->
 	<categoryProfile 
		name="categorie2"
		
		id="cp2"
		urlCategory="http://perso.univ-rennes1.fr:8080/raymond.bourges/categoryTest.xml"
		trustCategory="no"
		access="public"
		ttl = "3600" >
	 	<visibility>
	 		<allowed>
				<regular
					attribute="attr21"
					value="val21"/>
				<group
					name="group21"/>
			</allowed>			 
			<!-- autoSubscribed not yet supported -->
			<autoSubscribed>
				<regular
					attribute="attr22"
					value="val22"/>
				<group
					name="group22"/>
				<group
					name="group222"/>
			</autoSubscribed>
			<obliged>	
				<group
					name="local.0"/>
				
			</obliged>	
		</visibility>
	</categoryProfile>
		<categoryProfile 
		name="categorie3"
		id="cp3"
		urlCategory="http://perso.univ-rennes1.fr:8080/raymond.bourges/categoryTest.xml"
		trustCategory="no"
		access="public"
		ttl = "3600" >
		<visibility>
			<allowed>
				<regular
					attribute="attr31"
					value="val31"/>
				<group
					name="group31"/>
			</allowed>	
			<!-- autoSubscribed not yet supported -->	
			<autoSubscribed/>
			<obliged/>
		</visibility>
	</categoryProfile>
		<categoryProfile 
		name="categorie4"
		id="cp4"
		urlCategory="http://perso.univ-rennes1.fr:8080/raymond.bourges/categoryTest.xml"
		trustCategory="no"
		access="public"
		ttl = "3600" > 
		<visibility>
			<allowed>
				<regular
					attribute="attr41"
					value="val41"/>
				<group
					name="group41"/>
			</allowed>
			<!-- autoSubscribed not yet supported -->
			<autoSubscribed>
				<regular
					attribute="attr42"
					value="val42"/>
				<group
					name="group42"/>
				<group
					name="group422"/>
			</autoSubscribed>
			<obliged>
				<regular
					attribute="attr43"
					value="val43"/>	
			</obliged>
		</visibility>
	</categoryProfile>
</channelConfig>
