=== EsupPortail/esup-lecture/properties/esup-lecture.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT channelConfig (userId?, guestUser?, context*, categoryProfile*)>

<!ELEMENT userId (#PCDATA)> <!-- deprecated since 0.8.4 -->
<!ELEMENT guestUser (#PCDATA)>
<!ELEMENT context (description,refCategoryProfile*)>
<!ATTLIST context
    name CDATA #REQUIRED
	id ID #REQUIRED
    treeVisible (yes|no) "yes"
    edit (all|personal|managed|no) "no">

<!ELEMENT description (#PCDATA)>

<!ELEMENT refCategoryProfile EMPTY>
<!ATTLIST refCategoryProfile 
    refId IDREF #REQUIRED>

<!ELEMENT categoryProfile (visibility)>
<!ATTLIST categoryProfile
    id ID #REQUIRED
	name CDATA #REQUIRED
    urlCategory CDATA #REQUIRED
    trustCategory (yes|no) "no"
    edit (all|personal|managed|no) "no"
    access (public|cas) "public"
    userCanMarkRead (yes|no) "yes"
    ttl CDATA #REQUIRED
    timeout CDATA #REQUIRED>	
    
<!ELEMENT visibility (allowed,autoSubscribed,obliged)>

<!ELEMENT allowed (regular*, group*)>
<!ELEMENT autoSubscribed (regular*, group*)>
<!ELEMENT obliged (regular*, group*)>

<!ELEMENT regular EMPTY>
<!ATTLIST regular 
    attribute CDATA #REQUIRED
    value CDATA #REQUIRED>

<!ELEMENT group EMPTY>
<!ATTLIST group 
    name CDATA #REQUIRED>

=== EsupPortail/esup-lecture/properties/esup-lecture.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE channelConfig SYSTEM "esup-lecture.dtd" [
<!ENTITY repConf "file:///d:/tmp/conf_lecture_gwe_ray/" >
]>
<channelConfig>

	<!-- user attribute to define a user Id -->
	<userId>username</userId>

	<context name="CRI" id="default">
		<description>
			<![CDATA[
<h1>Portlet Lecture du CRI</h1>
Version de test. Merci de signaler tout problème à <a title="Envoyer un mail à raymond.bourges@univ-rennes1.fr" href="mailto:raymond.bourges@univ-rennes1.fr">raymond.bourges@univ-rennes1.fr</a>
]]>
		</description>
		<refCategoryProfile refId="liens" />
		<refCategoryProfile refId="rss" />
	</context>

	<categoryProfile name="Les liens utiles au CRI" id="liens"
		urlCategory="&repConf;liens.xml"
		trustCategory="no" access="public" ttl="3600" timeout="3000">
		<visibility>
			<allowed />
			<autoSubscribed />
			<obliged>
				<regular attribute="username" value="admin"/>
				<group name="pags.PERS_957" />
			</obliged>
		</visibility>
	</categoryProfile>

	<categoryProfile name="Les rss utiles au CRI" id="rss"
		urlCategory="&repConf;rss.xml"
		trustCategory="no" access="public" ttl="3600" timeout="3000">
		<visibility>
			<allowed />
			<autoSubscribed />
			<obliged>
				<regular attribute="username" value="admin"/>
				<group name="pags.PERS_957" />
			</obliged>
		</visibility>
	</categoryProfile>

</channelConfig>

=== EsupPortail/esup-lecture/properties/esup-lecture.vr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE channelConfig SYSTEM "esup-lecture.dtd" [
<!ENTITY repConf "file:///data/webapps/ent.univ-rennes1.fr/application/uPortal/html/esup-lecture/"
>
]
>
<!-- <!ENTITY repConf "http://localhost:8854/html/esup-lecture/" > -->

<channelConfig>
	<guestUser>guest</guestUser>
	
	<context 
	  name = "Actualités"
	  id = "default">
	  <description>Actualités Rennes 1</description> 
	  <refCategoryProfile refId="annonces"/>         <!-- portlet news : categorie Annonces Rennes 1 -->
	  <refCategoryProfile refId="annonces-ufr"/>     <!-- portlet news : categorie Annonces publiques UFR  -->
	  <refCategoryProfile refId="rss-rennes1"/>      <!-- fils rss Rennes 1 -->
	  <refCategoryProfile refId="rss-accueil-ent"/>      <!-- fils rss accueil ENT -->
      <refCategoryProfile refId="rss-ville-rennes"/> <!-- fils rss ville de Rennes -->
	  <refCategoryProfile refId="presse"/>           <!-- fils rss presse -->
	  <!-- url vers newsPortlet : renvoie un ensemble de categoryProfile -->
		<categoryProfilesUrl 
			url="http://ent-test.univ-rennes1.fr/html/esup-lecture/categoryProfilesUrl-test1.xml" 
			timeout=""
			idPrefix="test1"
		/>

	</context>

	<context 
	  name = "Actualités"
	  id = "IEP">
	  <description>Annonces</description> 
	  <refCategoryProfile refId="annonces-iep"/>     <!-- portlet news : categorie Annonces IEP -->
	</context>

	<context 
	  name = "Actualités"
	  id = "ENSCR">
	  <description>Annonces</description> 
	  <refCategoryProfile refId="annonces-enscr"/>   <!-- portlet news : categorie Annonces IEP -->
	</context>

 	<categoryProfile 
		name="categorie fils RSS Rennes 1"
		id="rss-rennes1"
		urlCategory="&repConf;rss-rennes1.xml"
		trustCategory="no"
		access="public"
		ttl = "3600"
		timeout = "3000">
	 	<visibility>
	 	<!-- allowed and autoSubscribed supported -->
	 		<allowed/>
			<autoSubscribed/>
			<obliged>	
				<group name="local.101"/> <!-- Etablissement -->
			</obliged>	
		</visibility>
	</categoryProfile>

 	<categoryProfile 
		name="categorie fils RSS accueil ENT"
		id="rss-accueil-ent"
		urlCategory="&repConf;rss-accueil-ent.xml"
		trustCategory="no"
		access="public"
		ttl = "3600"
		timeout = "3000">
	 	<visibility>
	 	<!-- allowed and autoSubscribed supported -->
	 		<allowed/>
			<autoSubscribed/>
			<obliged>	
				<group name="local.15"/> <!-- Anonymes -->
			</obliged>	
		</visibility>
	</categoryProfile>

 	<categoryProfile 
		name="categorie fils RSS ville de Rennes"
		id="rss-ville-rennes"
		urlCategory="&repConf;rss-ville-rennes.xml"
		trustCategory="no"
		access="public"
		ttl = "3600"
		timeout = "3000">
	 	<visibility>
	 	<!-- allowed and autoSubscribed not yet supported -->
	 		<allowed/>
			<autoSubscribed/>
			<obliged>	
				<group name="local.101"/> <!-- Etablissement -->
			</obliged>	
		</visibility>
	</categoryProfile>

 	<categoryProfile 
		name="categorie annonces Rennes 1"
		id="annonces"
		urlCategory="http://localhost:8854/newsPortlet/feeds/pub/rss?t=3&#38;cID=3"
		trustCategory="yes"
		access="public"
		ttl = "3600"
		timeout = "3000">
	 	<visibility>
	 	<!-- allowed and autoSubscribed not yet supported -->
	 		<allowed/>
			<autoSubscribed/>
			<obliged>	
				<group name="local.101"/> <!-- Etablissement -->
			</obliged>	
		</visibility>
	</categoryProfile>

 	<categoryProfile 
		name="annonces publiques UFR"
		id="annonces-ufr"
		urlCategory="http://localhost:8854/newsPortlet/feeds/pub/rss?t=3&#38;cID=24"
		trustCategory="yes"
		access="public"
		ttl = "3600"
		timeout = "3000">
	 	<visibility>
	 	<!-- allowed and autoSubscribed not yet supported -->
	 		<allowed/>
			<autoSubscribed/>
			<obliged>	
				<group name="local.101"/> <!-- Etablissement -->
			</obliged>	
		</visibility>
	</categoryProfile>


 	<categoryProfile 
		name="categorie annonces IEP"
		id="annonces-iep"
		urlCategory="http://localhost:8854/newsPortlet/feeds/pub/rss?t=3&#38;cID=4"
		trustCategory="yes"
		access="public"
		ttl = "3600"
		timeout = "3000">
	 	<visibility>
	 	<!-- allowed and autoSubscribed not yet supported -->
	 		<allowed/>
			<autoSubscribed/>
			<obliged>	
				<group name="local.205"/> <!-- Etablissement IEP -->
			</obliged>	
		</visibility>
	</categoryProfile>


 	<categoryProfile 
		name="categorie annonces ENSCR"
		id="annonces-enscr"
		urlCategory="http://localhost:8854/newsPortlet/feeds/pub/rss?t=3&#38;cID=5"
		trustCategory="yes"
		access="public"
		ttl = "3600"
		timeout = "3000">
	 	<visibility>
	 	<!-- allowed and autoSubscribed not yet supported -->
	 		<allowed/>
			<autoSubscribed/>
			<obliged>	
				<group name="local.128"/> <!-- Etablissement ENSCR -->
			</obliged>	
		</visibility>
	</categoryProfile>

 	<categoryProfile 
		name="categorie presse"
		id="presse"
		urlCategory="&repConf;presse.xml"
		trustCategory="no"
		access="public"
		ttl = "3600"
		timeout = "3000">
	 	<visibility>
	 	<!-- allowed and autoSubscribed not yet supported -->
	 		<allowed>
				<group name="local.101"/> <!-- Etablissement -->
			</allowed>
			<autoSubscribed/>
			<obliged/>	
		</visibility>
	</categoryProfile>

</channelConfig>

=== EsupPortail/esup-lecture/properties/esup-lecture.example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE channelConfig SYSTEM "esup-lecture.dtd" [
<!ENTITY repConf "file:///data/webapps/ent.univ-rennes1.fr/application/esup-lecture/properties" >
<!ENTITY httpConf "http://ent.univ-rennes1.fr/"
>
]
>

<channelConfig>
	<ttl>0</ttl>
	<guestUser>guest</guestUser>
	<context 
		name = "Actualités"
		id = "default">
		<description>Actualités</description> 
		<refCategoryProfile refId="annonces"/>         <!-- portlet news : categorie Annonces Rennes 1 -->
		<refCategoryProfile refId="rss-rennes1"/>      <!-- fils rss Rennes 1 -->
		<categoryProfilesUrl 
			url="&repConf;categories-canalu.example.xml" 
			timeout=""
			idPrefix="canalu"
		/> <!-- fils canalu : categories definies ailleurs -->
	</context>

	<context 
	  name = "Presse"
	  id = "presse">
	  <description>Annonces de la recherche</description> 
		<refCategoryProfile refId="presse"/> 	         <!-- fils rss presse -->
	</context>

	<categoryProfile 
		name="categorie annonces Rennes 1"
		id="annonces"
		urlCategory="&httpConf;newsPortlet/feeds/pub/rss?t=3&#38;cID=3"
		trustCategory="yes"
		access="public"
		ttl = "3600"
		timeout = "3000">
	 	<visibility>
	 		<allowed/>
			<autoSubscribed/>
			<obliged>	
				<group name="local.101"/> <!-- Etablissement -->
				<group name="pags.LECTEURS"/>
				<group name="pags.RETRAITESPERS"/>
			</obliged>	
		</visibility>
	</categoryProfile>

 	<categoryProfile 
		name="categorie fils RSS Rennes 1"
		id="rss-rennes1"
		urlCategory="&repConf;rss-rennes1.example.xml"
		trustCategory="no"
		access="public"
		ttl = "3600"
		timeout = "3000">
	 	<visibility>
	 		<allowed/>
			<autoSubscribed>	
				<group name="local.101"/> <!-- Etablissement -->
				<group name="pags.LECTEURS"/>
				<group name="pags.RETRAITESPERS"/>
			</autoSubscribed>	
			<obliged/>	
		</visibility>
	</categoryProfile>

	<categoryProfile 
		name="categorie presse"
		id="presse"
		urlCategory="&repConf;presse.example.xml"
		trustCategory="no"
		access="public"
		ttl = "3600"
		timeout = "3000">
	 	<visibility>
	 		<allowed>
				<group name="local.101"/> 
				<group name="pags.RETRAITESPERS"/>
			</allowed>
			<autoSubscribed/>
			<obliged/>	
		</visibility>
	</categoryProfile>

</channelConfig>
