=== EsupPortail/esup-lecture/src/main/resources/properties/examples/xml/category.dtd
<!ENTITY config.url.prefix "${config.url.prefix}">

<!ELEMENT category (description,sourceProfiles, visibility?)>
<!ATTLIST category
    name CDATA #REQUIRED
    edit (all|personal|managed|no) "no">
<!ELEMENT description (#PCDATA)>
<!ELEMENT sourceProfiles (sourceProfile+)>

<!ELEMENT sourceProfile (visibility?)>
<!ATTLIST sourceProfile
    id ID #REQUIRED
    name CDATA #REQUIRED
    url CDATA #REQUIRED
    xslt CDATA #IMPLIED
    mobileXslt CDATA #IMPLIED
    xpath CDATA #IMPLIED
    access (public|cas) #IMPLIED
    specificUserContent (yes|no) "no"
    timeout CDATA #IMPLIED>

<!ELEMENT visibility (allowed,autoSubscribed,obliged)>

<!ELEMENT allowed (regular*, regex*, group*, guest?)>
<!ELEMENT autoSubscribed (regular*, regex*, group*, guest?)>
<!ELEMENT obliged (regular*, regex*, group*, guest?)>

<!ELEMENT regular EMPTY>
<!ATTLIST regular
    attribute CDATA #REQUIRED
    value CDATA #REQUIRED>

<!ELEMENT regex EMPTY>
<!ATTLIST regex
    attribute CDATA #REQUIRED
    pattern CDATA #REQUIRED>

<!ELEMENT group EMPTY>
<!ATTLIST group name CDATA #REQUIRED>

<!ELEMENT guest EMPTY>

=== EsupPortail/esup-lecture/src/main/resources/properties/examples/xml/category.offline.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE category SYSTEM "category.dtd">
<category edit="all" name="Exemples">
	<description>Exemples</description>
	<sourceProfiles>
		<!-- rss-jquery-clickable.xsl -->
		<sourceProfile id="un" access="public"
			name="Divers liens (rss-jquery-clickable)" specificUserContent="no"
			url="&config.url.prefix;/examples/xml/flux.offline1.xml">
			<visibility>
				<allowed></allowed>
				<autoSubscribed>
                                    <group name="local.0" />  <!-- Tous les groupes de personnes -->
                                </autoSubscribed>
				<obliged>
                                    <group name="local.15" /> <!-- Anonymes -->
				</obliged>
			</visibility>
		</sourceProfile>
		<!-- rss-jquery-inline.xsl -->
		<sourceProfile id="deux" access="public"
			name="Divers liens (rss-jquery-inline)" specificUserContent="no"
			url="&config.url.prefix;/examples/xml/flux.offline2.xml">
			<visibility>
				<allowed>
					<group name="local.0" />  <!-- Tous les groupes de personnes -->                                    
                                </allowed>
				<autoSubscribed></autoSubscribed>
				<obliged>
					<group name="local.15" /> <!-- Anonymes -->
				</obliged>
			</visibility>
		</sourceProfile>
		<!-- rss-jquery-dialog.xsl -->
		<sourceProfile id="trois" access="public"
			name="Divers liens (rss-jquery-dialog)" specificUserContent="no"
			url="&config.url.prefix;/examples/xml/flux.offline3.xml">
			<visibility>
				<allowed></allowed>
				<autoSubscribed></autoSubscribed>
				<obliged>
					<group name="local.0" />  <!-- Tous les groupes de personnes -->
					<group name="local.15" /> <!-- Anonymes -->
				</obliged>
			</visibility>
		</sourceProfile>
 		<sourceProfile id="quatre" access="public"
			name="Actus de Rennes 1" specificUserContent="no"
			url="http://www.univ-rennes1.fr/bas-de-page/RSS/actualites/">
			<visibility>
				<allowed></allowed>
				<autoSubscribed></autoSubscribed>
				<obliged>
					<group name="local.0" />
					<group name="local.15" />
				</obliged>
			</visibility>
		</sourceProfile>
<!--  test CAS en portlet
 		<sourceProfile id="trois" access="cas"
			name="Actus de Rennes 1 (en CAS)" specificUserContent="no"
			url="http://uportal.univ-rennes1.fr/flux-cas/media/Actualites.xml">
			<visibility>
				<allowed></allowed>
				<autoSubscribed></autoSubscribed>
				<obliged>
					<group name="local.0" />  
					<group name="local.15" />  
				</obliged>
			</visibility>
		</sourceProfile>
-->		

<!--  test CAS en servlet -->
<!--  		<sourceProfile id="trois" access="cas" -->
<!-- 			name="Actus de Rennes 1 (en CAS)" specificUserContent="no" -->
<!-- 			url="http://uportal.univ-rennes1.fr/media/Actualites.xml"> -->
<!-- 			<visibility> -->
<!-- 				<allowed></allowed> -->
<!-- 				<autoSubscribed></autoSubscribed> -->
<!-- 				<obliged> -->
<!-- 					<group name="local.0" />   -->
<!-- 					<group name="local.15" />   -->
<!-- 				</obliged> -->
<!-- 			</visibility> -->
<!-- 		</sourceProfile> -->
		
	</sourceProfiles>

	<visibility>
		<allowed>
			<group name="local.0" />                    
                </allowed>
		<autoSubscribed></autoSubscribed>
		<obliged>
			<group name="local.15" />
		</obliged>
	</visibility>
</category>

=== EsupPortail/esup-lecture/src/main/resources/properties/category.offline.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE category SYSTEM "category.dtd">
<category edit="all" name="Presse">
	<description>Exemples</description>
	<sourceProfiles>
		<sourceProfile id="un" access="public"
			name="Outils pÃ©dagogique de Rennes 1" specificUserContent="no"
			url="${config.url.prefix}/flux.offline.xml">
			<visibility>
				<allowed></allowed>
				<autoSubscribed></autoSubscribed>
				<obliged>
					<group name="local.0" />  <!-- Tous les groupes de personnes -->
					<group name="local.15" /> <!-- Anonymes -->
				</obliged>
			</visibility>
		</sourceProfile>

		<!-- <sourceProfile id="deux" access="public" name="LeMonde.fr : International" 
			specificUserContent="no" ttl="86400" url="http://www.lemonde.fr/rss/sequence/0,2-3210,1-0,0.xml"> 
			<visibility> <obliged> <group name="local.0" /> <group name="local.15" /> 
			</obliged> </visibility> </sourceProfile> <sourceProfile id="trois" access="public" 
			name="L'Equipe.fr : Actu Sport" specificUserContent="no" ttl="86400" url="http://www.lequipe.fr/Xml/actu_rss.xml"> 
			<visibility> <obliged> <group name="local.0" /> <group name="local.15" /> 
			</obliged> </visibility> </sourceProfile> -->

	</sourceProfiles>
	<visibility>
		<allowed></allowed>
		<autoSubscribed></autoSubscribed>
		<obliged>
			<group name="local.0" />
			<group name="local.15" />
		</obliged>
	</visibility>
</category>

=== EsupPortail/esup-lecture/src/main/resources/properties/examples/xml/demo3.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE category SYSTEM "category.dtd">
<!-- Category for proxy cas tests -->
<category edit="all" name="Jeux !">
	<description>CAS tests (Un Jeu en flash en direct)</description>
	<sourceProfiles>
		<sourceProfile id="un" access="cas" name="RSS Jeux en Flash"
			specificUserContent="no"
			url="http://uportal.univ-rennes1.fr/testCAS/jeux-flash.xml">
			<visibility>
				<allowed></allowed>
				<autoSubscribed></autoSubscribed>
				<obliged>
					<group name="local.0" />
				</obliged>
			</visibility>
		</sourceProfile>
	</sourceProfiles>
	<visibility>
		<allowed></allowed>
		<autoSubscribed></autoSubscribed>
		<obliged>
			<group name="local.0" />
		</obliged>
	</visibility>

</category>

=== EsupPortail/esup-lecture/src/main/resources/properties/presse.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE category SYSTEM "category.dtd">
<category edit="all" name="Presse" ttl="">
	<description>Actualités Bretagne</description>
	<sourceProfiles>
		<sourceProfile id="un" access="public" name="Bretagne" 
		 specificUserContent="no" ttl="86400" url="http://www.lemonde.fr/rss/une.xml">
			<visibility>
				<obliged>
					<group name="local.0"/>  <!-- Tous les groupes de personnes -->
				</obliged>
			</visibility>		
		</sourceProfile>
		
		<sourceProfile id="deux" access="public" name="LeMonde.fr : International" 
		 specificUserContent="no" ttl="86400" url="http://www.lemonde.fr/rss/sequence/0,2-3210,1-0,0.xml">
			<visibility>
				<obliged>
					<group name="local.0"/>  <!-- Tous les groupes de personnes -->
				</obliged>
			</visibility>		
		</sourceProfile>
		
		<sourceProfile id="trois" access="public" name="L'Equipe.fr : Actu Sport" 
		 specificUserContent="no" ttl="86400" url="http://www.lequipe.fr/Xml/actu_rss.xml">
			<visibility>
				<obliged>
					<group name="local.0"/>  <!-- Tous les groupes de personnes -->
				</obliged>
			</visibility>		
		</sourceProfile>
		
	</sourceProfiles>
	<visibility>
		<obliged>
			<group name="local.0"/>
		</obliged>
	</visibility>
</category>

=== EsupPortail/esup-lecture/src/main/resources/properties/actubretagne.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE category SYSTEM "category.dtd">
<category edit="all" name="Infos Bretagne" ttl="3600">
	<description>Infos Bretagne</description>
	<sourceProfiles>
		<sourceProfile id="insa1" access="public"
			name="Actus Bretagne" specificUserContent="no" ttl="86400"
			url="http://www.bretagne.fr/internet/feed/Rss2.jsp?id=JB080118_6262&#38;pcat=j_6">
			<visibility>
				<obliged>
				<group name="local.0"/>  <!-- Tous les groupes de personnes -->				
				</obliged>
			</visibility>
		</sourceProfile>
		<sourceProfile id="insa2" access="public"
			name="Actus Departement" specificUserContent="no" ttl="86400"
			url="http://www.ille-et-vilaine.fr/index.php?cmpref=735&#38;parentref=90429&#38;module=news&#38;action=ViewFeed">
			<visibility>
				<obliged>
				<group name="local.0"/>  <!-- Tous les groupes de personnes -->
				</obliged>
			</visibility>
		</sourceProfile>
		<sourceProfile id="insa3" access="public"
			name="Actus (Rennes Metropole) specificUserContent="no" ttl="86400"
			url="http://www.rennes-metropole.fr/?syndicationParam[idFeed]=149599&#38;syndicationParam[type]=rss&#38;module=syndication&#38;action=GetSyndication">
			<visibility>
				<obliged>
				<group name="local.0"/>  <!-- Tous les groupes de personnes -->
				</obliged>
			</visibility>
		</sourceProfile>
		<sourceProfile id="insa4" access="public"
                        name="Actus Recherche (Rennes Metropole)" specificUserContent="no" ttl="86400"
                        url="http://www.rennes-metropole.fr/?syndicationParam[idFeed]=149610&#38;syndicationParam[type]=rss&#38;module=syndication&#38;action=GetSyndication">
                        <visibility>
                                <obliged>
                                <group name="local.0"/>  <!-- Tous les groupes de personnes -->
                                </obliged>
                        </visibility>
                </sourceProfile>
	</sourceProfiles>
</category>

=== EsupPortail/esup-lecture/src/test/resources/properties/examples/xml/demo2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE category SYSTEM "category.dtd">
<category edit="all" name="Jeux !">
	<description>Des jeux (RRS de jeux en Flash | Un Jeu en flash en direct
		| Un jeu sous forme d'une applet java)</description>
	<sourceProfiles>
		<sourceProfile id="trois" access="public" name="RSS Jeux en Flash"
			specificUserContent="no"
			url="&config.url.prefix;/examples/xml/jeux-flash.xml">
			<visibility>
				<allowed></allowed>
				<autoSubscribed></autoSubscribed>
				<obliged>
					<group name="local.0" />
				</obliged>
			</visibility>
		</sourceProfile>
		<sourceProfile id="cinq" access="public" name="Un jeu (applet java)"
			specificUserContent="no"
			url="&config.url.prefix;/examples/xml/jeu-java-seul.xml">
			<visibility>
				<allowed></allowed>
				<autoSubscribed></autoSubscribed>
				<obliged>
					<group name="local.0" />
				</obliged>
			</visibility>
		</sourceProfile>
	</sourceProfiles>
	<visibility>
		<allowed></allowed>
		<autoSubscribed></autoSubscribed>
		<obliged>
			<group name="local.0" />
		</obliged>
	</visibility>

</category>
